# Five Intresting Numpy Modules!

Write a short introduction about Numpy and list the chosen functions. 

- **np.linalg.solve(a,b)**     
- **np.linalg.det(a)**     
- **np.linalg.inv(a)**
- **np.linalg.matrix_rank(a)**
- **np.vdot(a,b)**

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [21]:
!pip install jovian --upgrade -q

In [22]:
import jovian

In [23]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sagarpartap-che18/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sagarpartap-che18/numpy-array-operations


'https://jovian.ai/sagarpartap-che18/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [24]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.linalg.solve(a,b)
function2 = np.linalg.det(a)
function3 = np.linalg.inv(a)
function4 = np.linalg.matrix_rank(a)
function5 = np.vdot(a,b)

## Function 1 - np.linalg.solve(a,b) 

**In Linear Algebra the matrix equation to solve a system of linear equation is given by:
A*X = B
*Where a & b are arrays or matrices.
'a' being the coefficient matrix
& 'b' being constant matrix*
NOTE : a & b are square matrices
Example : Let's say we have an equation 3x + y = 9 & x + 2y = 8 .
Now here, we can say that : a = [[3,1],[1,2]] & b = [9,4]**

In [25]:
# Example 1 - working (A system of 2 Linear Equation with two variables)
a = [[3, 1],[1, 2]]

b = [9, 8]

np.linalg.solve(a,b)

array([2., 3.])

The resulting array or 1d-matrix represents values of X = [x,y].
Here we can see we got x = 2 & y = 3.
We can check this by substitution methord as follows :
3x + y = 9 => y = 9 - 3x----(1)
x + 2y = 8 => x + 2*(9 - 3x) = 8 (on substituting value of y from (1))
x + 18 - 6x = 8
-5x + 18 = 8
x = (18 - 8) / 5 = 10 / 5 = 2
y = 9 - 3*x = 9 - 3*2 = 9 - 6 = 3
Hence x = 2 & y = 3 which matches our output!

In [26]:
# Example 2 - working (Just a variation with 3 variables)
a = [[6,2,-5],[3,3,-2],[7,5,-3]]
b = [13,13,26]

np.linalg.solve(a,b)

array([2., 3., 1.])

The resulting array or the solution matrix has 3 values as X = [x, y, z].
Where, x = 2 , y = 3 & z = 1.
We can check by substituting the values of x, y & z back to the equation it would equate to zero, hence would also satisfy the equation.

In [27]:
# Example 3 - breaking (to illustrate when it breaks)
a = [[1, 2, 6],[3, 4, 7]]

b = [5, 6]

np.linalg.solve(a,b)

LinAlgError: Last 2 dimensions of the array must be square

Explanation about the example:
The reason it throwed an LinAlgError was because the matrix a is always supposed to be a square matrix, i.e it must have equal number of rows and equal number of coloumns.
A quick fix to the problem is to assume the not given terms as zero.

Some closing comments about when to use this function.

## Function 2 - np.linalg.det(a)

This function is used to evaluate the determinant of a **square matrix 'a'**.

In [28]:
# Example 1 - working
a = [[1,2],
     [3,4]]
np.linalg.det(a)

-2.0000000000000004

The det of the matrix a is supposed to be the diffrence of product of the diagonal elements!
For extra information go here : https://en.wikipedia.org/wiki/Determinant

In [29]:
# Example 2 - working for a 3x3 matrix 'a'
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]
np.linalg.det(a)

6.66133814775094e-16

Explanation about example

In [30]:
# Example 3 - breaking (to illustrate when it breaks)
a = [1,2]
np.linalg.det(a)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

## Function 3 - np.linalg.inv(a) 

Inverse of the matrix a is supposed to be a matrix a'. Such that a*a' = I (Identity Matrix) i.e : I = [[1,0],[0,1]] (2D Identity Matrix)


In [31]:
# Example 1 - working
a = [[1,2],[3,4]]
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Explanation about example

In [32]:
# Example 2 - working 3x3 matrix a and its inverse
a = [[4,5,3],
     [2,7,8],
     [5,2,9]]
np.linalg.inv(a)

array([[ 0.22926829, -0.1902439 ,  0.09268293],
       [ 0.10731707,  0.10243902, -0.12682927],
       [-0.15121951,  0.08292683,  0.08780488]])

Explanation about example

In [33]:
# Example 3 - breaking (to illustrate when it breaks)
a = [[1,2,7],
     [5,3,4]]
np.linalg.inv(a)

LinAlgError: Last 2 dimensions of the array must be square

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 4 - np.linalg.matrix_rank(M, tol=??, hermitian=??)

Add some explanations

In [34]:
# Example 1 - working 3x3 matrix a and its rank
a = [[0,0,0],
     [0,2,1],
     [0,0,0]]
np.linalg.matrix_rank(a)

1

Explanation about example

In [35]:
# Example 2 - working
np.linalg.matrix_rank(np.eye(4)) #Full rank Matrix

4

Explanation about example

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
a = []
np.linalg.matrix_rank(a)

0

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 5 - np.vdot(a, b)

Add some explanations

In [37]:
# Example 1 - working
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(a, b)

(70-8j)

Explanation about example

In [38]:
# Example 2 - working
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(b, a)

(70+8j)

Explanation about example

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(a)

TypeError: vdot() missing 1 required positional argument: 'b'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [40]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sagarpartap-che18/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sagarpartap-che18/numpy-array-operations


'https://jovian.ai/sagarpartap-che18/numpy-array-operations'